import type { Editor } from "@/components/editor/editor";
import {
  ShapeType,
  type RectangleShape,
  type EllipseShape,
} from "@/components/editor/shapes";
import { odd } from "@/lib/utils";

interface U8g2State {
  drawColor: number;
  font: string;
  fontDirection: number;
}

/**
 * Code generator class
 */
export class CodeGenerator {
  editor: Editor;

  constructor(editor: Editor) {
    this.editor = editor;
  }

  toU8g2Color(color: number): number {
    return color < 0 ? 2 : color;
  }

  generateU8g2Rectangle(state: U8g2State, shape: RectangleShape): string[] {
    const lines: string[] = [];
    lines.push(`// ${shape.name}`);
    const { left, top, width, height, color } = shape;
    if (state.drawColor !== color) {
      lines.push(`u8g2.setDrawColor(${this.toU8g2Color(color)});`);
      state.drawColor = color;
    }
    if (shape.fill) {
      lines.push(`u8g2.drawBox(${left}, ${top}, ${width}, ${height});`);
    } else {
      lines.push(`u8g2.drawFrame(${left}, ${top}, ${width}, ${height});`);
    }
    return lines;
  }

  generateU8g2Ellipse(state: U8g2State, shape: EllipseShape): string[] {
    const lines: string[] = [];
    lines.push(`// ${shape.name}`);
    const { left, top, width, height, color } = shape;
    const cx = Math.round(left + width / 2);
    const cy = Math.round(top + height / 2);
    const rx = Math.round(width / 2) - 1;
    const ry = Math.round(height / 2) - 1;
    if (state.drawColor !== color) {
      lines.push(`u8g2.setDrawColor(${this.toU8g2Color(color)});`);
      state.drawColor = color;
    }
    if (!odd(shape.width) || !odd(shape.height)) {
      lines.push(
        `// [WARNING] Ellipse with even width or height may not render correctly`,
      );
    }
    if (shape.fill) {
      lines.push(`u8g2.drawFilledEllipse(${cx}, ${cy}, ${rx}, ${ry});`);
    } else {
      lines.push(`u8g2.drawEllipse(${cx}, ${cy}, ${rx}, ${ry});`);
    }
    return lines;
  }

  /**
   * Generates U8g2 code
   */
  generateU8g2(editor: Editor): string {
    const state: U8g2State = {
      drawColor: 1,
      font: "u8g2_font_ncenB14_tr",
      fontDirection: 0,
    };
    const lines: string[] = [];
    lines.push("// [BEGIN] generated by Empix");
    const shapes = editor.store.shapes;
    for (let i = 0; i < shapes.length; i++) {
      const shape = shapes[i];
      switch (shape.type) {
        case ShapeType.RECTANGLE:
          lines.push(
            ...this.generateU8g2Rectangle(state, shape as RectangleShape),
          );
          break;
        case ShapeType.ELLIPSE:
          lines.push(...this.generateU8g2Ellipse(state, shape as EllipseShape));
          break;
        case ShapeType.LINE:
          lines.push(
            `drawLine(${shape.left}, ${shape.top}, ${shape.width}, ${shape.height}, ${shape.color});`,
          );
          break;
        case ShapeType.TEXT:
          lines.push(
            `drawText(${shape.left}, ${shape.top}, "${(shape as any).text}", ${shape.color});`,
          );
          break;
        case ShapeType.PEN:
          lines.push(
            `drawPen(${(shape as any).points.map(
              (p: any) => `[${p[0]}, ${p[1]}]`,
            )}, ${shape.color});`,
          );
          break;
        default:
          console.warn(`Unknown shape type: ${shape.type}`);
      }
    }
    lines.push("// [END] generated by Empix");
    return lines.join("\n");
  }
}
