import type { Editor } from "@/components/editor/editor";
import { ShapeType } from "@/components/editor/shapes";

/**
 * Code generator class
 */
export class CodeGenerator {
  editor: Editor;

  constructor(editor: Editor) {
    this.editor = editor;
  }

  /**
   * Generates U8g2 code
   */
  generateU8g2(editor: Editor): string {
    let code = "// Code generated by Empix\n";
    const shapes = editor.store.shapes;
    for (let i = 0; i < shapes.length; i++) {
      const shape = shapes[i];
      switch (shape.type) {
        case ShapeType.RECTANGLE:
          code += `drawRectangle(${shape.left}, ${shape.top}, ${shape.width}, ${shape.height}, ${shape.color});\n`;
          break;
        case ShapeType.ELLIPSE:
          code += `drawEllipse(${shape.left}, ${shape.top}, ${shape.width}, ${shape.height}, ${shape.color});\n`;
          break;
        case ShapeType.LINE:
          code += `drawLine(${shape.left}, ${shape.top}, ${shape.width}, ${shape.height}, ${shape.color});\n`;
          break;
        case ShapeType.TEXT:
          code += `drawText(${shape.left}, ${shape.top}, "${(shape as any).text}", ${shape.color});\n`;
          break;
        case ShapeType.PEN:
          code += `drawPen(${(shape as any).points.map(
            (p: any) => `[${p[0]}, ${p[1]}]`,
          )}, ${shape.color});\n`;
          break;
        default:
          console.warn(`Unknown shape type: ${shape.type}`);
      }
    }
    return code;
  }
}
